// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8yKNTg6SHnChDP0bElt1TI4PTTrV1qSo',
    appId: '1:784463954015:web:eb3237d2d43b597d4b5bea',
    messagingSenderId: '784463954015',
    projectId: 'master-esgul-assignment-app',
    authDomain: 'master-esgul-assignment-app.firebaseapp.com',
    storageBucket: 'master-esgul-assignment-app.firebasestorage.app',
    measurementId: 'G-9J3YTFPJ79',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBq7t2A-Y9Sq7HjYoq7HLcmZfKHqDBfhEI',
    appId: '1:784463954015:android:01b0f5e84cf115604b5bea',
    messagingSenderId: '784463954015',
    projectId: 'master-esgul-assignment-app',
    storageBucket: 'master-esgul-assignment-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDd8_sWD4dmQgfXFAzcmbHtopHN7mZFCSY',
    appId: '1:784463954015:ios:c463ea61c1c406f04b5bea',
    messagingSenderId: '784463954015',
    projectId: 'master-esgul-assignment-app',
    storageBucket: 'master-esgul-assignment-app.firebasestorage.app',
    iosBundleId: 'com.example.peopleManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDd8_sWD4dmQgfXFAzcmbHtopHN7mZFCSY',
    appId: '1:784463954015:ios:c463ea61c1c406f04b5bea',
    messagingSenderId: '784463954015',
    projectId: 'master-esgul-assignment-app',
    storageBucket: 'master-esgul-assignment-app.firebasestorage.app',
    iosBundleId: 'com.example.peopleManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8yKNTg6SHnChDP0bElt1TI4PTTrV1qSo',
    appId: '1:784463954015:web:3ff3474d3f81f0904b5bea',
    messagingSenderId: '784463954015',
    projectId: 'master-esgul-assignment-app',
    authDomain: 'master-esgul-assignment-app.firebaseapp.com',
    storageBucket: 'master-esgul-assignment-app.firebasestorage.app',
    measurementId: 'G-ZQ82JW92HH',
  );
}
